// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// The availability of an on-device generative AI feature.
enum EdgeGenAIAvailability: Int, CaseIterable {
  /// The feature is available and ready to use.
  case available = 0
  /// The device supports the feature, but it still needs to download (for
  /// example, Android's Gemini Nano feature is downloadable/downloading).
  case downloadable = 1
  /// The device supports the feature, but the user hasn't enabled the
  /// OS-level AI feature yet (for example, Apple Intelligence is turned
  /// off).
  case notYetReady = 2
  /// The device or OS version doesn't support the on-device feature.
  case unavailable = 3
}

/// The on-device generative AI features exposed by this plugin.
///
/// On Android each feature is a distinct ML Kit GenAI client with its own
/// independent availability/download lifecycle; on iOS they all map to the
/// single system Foundation Models availability.
enum EdgeGenAIFeature: Int, CaseIterable {
  /// The general-purpose prompt feature (`EdgeGenAIPrompt`).
  case prompt = 0
  /// The text summarization feature (`EdgeGenAISummarizer`).
  case summarization = 1
  /// The proofreading feature (`EdgeGenAIProofreader`).
  case proofreading = 2
  /// The text rewriting feature (`EdgeGenAIRewriter`).
  case rewriting = 3
  /// The image description feature (`EdgeGenAIImageDescriber`).
  case imageDescription = 4
}

/// The style `EdgeGenAIRewriter` rewrites text into.
///
/// Matches the output types of Android's ML Kit GenAI Rewriting API; on iOS
/// each style becomes a task-specific instruction to the system model.
enum EdgeGenAIRewriteStyle: Int, CaseIterable {
  /// Rephrases the text while keeping its meaning and length.
  case rephrase = 0
  /// Expands on the text with more detail.
  case elaborate = 1
  /// Adds fitting emoji to the text.
  case emojify = 2
  /// Shortens the text while keeping its meaning.
  case shorten = 3
  /// Rewrites the text in a casual, friendly tone.
  case friendly = 4
  /// Rewrites the text in a formal, professional tone.
  case professional = 5
}

/// The status of an on-device model download.
enum EdgeGenAIDownloadStatus: Int, CaseIterable {
  /// The download has started.
  case started = 0
  /// The download is in progress.
  case inProgress = 1
  /// The download finished and the model is ready to use.
  case completed = 2
}

/// The model-facing description of a tool the app exposes to the model.
///
/// The tool's implementation stays in Dart (see `EdgeGenAITool.onCall`);
/// only this schema crosses to the platform side, which calls back into
/// Dart via `EdgeGenAIToolExecutorApi` when the model invokes the tool.
///
/// The description field is named `descriptionText` (not `description`)
/// because Pigeon reserves `description` for Swift's NSObject property.
///
/// Generated class from Pigeon that represents data sent in messages.
struct EdgeGenAIToolDefinition: Hashable, CustomStringConvertible {
  /// The tool's unique name.
  var name: String
  /// What the tool does, so the model knows when to call it.
  var descriptionText: String
  /// A JSON Schema document (as JSON text) describing the tool's arguments
  /// object: `{"type": "object", "properties": {...}, "required": [...]}`.
  ///
  /// It's carried as JSON text rather than typed Pigeon classes because
  /// schemas are recursive (objects nest objects, arrays have item
  /// schemas), which Pigeon data classes can't express. The supported
  /// subset — mirroring what Foundation Models' `DynamicGenerationSchema`
  /// can enforce — is: `type` (string/number/integer/boolean/array/object),
  /// `description`, `enum` (strings), `minimum`/`maximum` (numbers),
  /// `items`/`minItems`/`maxItems` (arrays), and `properties`/`required`
  /// (objects). The `EdgeGenAIToolSchema` factories in Dart only build
  /// this subset.
  var parametersSchemaJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EdgeGenAIToolDefinition? {
    let name = pigeonVar_list[0] as! String
    let descriptionText = pigeonVar_list[1] as! String
    let parametersSchemaJson = pigeonVar_list[2] as! String

    return EdgeGenAIToolDefinition(
      name: name,
      descriptionText: descriptionText,
      parametersSchemaJson: parametersSchemaJson
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      descriptionText,
      parametersSchemaJson,
    ]
  }
  static func == (lhs: EdgeGenAIToolDefinition, rhs: EdgeGenAIToolDefinition) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.descriptionText, rhs.descriptionText) && MessagesPigeonInternal.deepEquals(lhs.parametersSchemaJson, rhs.parametersSchemaJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EdgeGenAIToolDefinition")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: descriptionText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: parametersSchemaJson, hasher: &hasher)
  }

  public var description: String {
    return "EdgeGenAIToolDefinition(name: \(String(describing: name)), descriptionText: \(String(describing: descriptionText)), parametersSchemaJson: \(String(describing: parametersSchemaJson)))"
  }
}

/// Optional parameters controlling how the model generates its response.
///
/// Only fields supported by both Android and iOS are exposed here.
///
/// Generated class from Pigeon that represents data sent in messages.
struct EdgeGenAIGenerationOptions: Hashable, CustomStringConvertible {
  /// Controls the randomness of the output. Higher values produce more
  /// creative (less predictable) responses.
  var temperature: Double? = nil
  /// The maximum number of tokens the model may generate in its response.
  var maxOutputTokens: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EdgeGenAIGenerationOptions? {
    let temperature: Double? = nilOrValue(pigeonVar_list[0])
    let maxOutputTokens: Int64? = nilOrValue(pigeonVar_list[1])

    return EdgeGenAIGenerationOptions(
      temperature: temperature,
      maxOutputTokens: maxOutputTokens
    )
  }
  func toList() -> [Any?] {
    return [
      temperature,
      maxOutputTokens,
    ]
  }
  static func == (lhs: EdgeGenAIGenerationOptions, rhs: EdgeGenAIGenerationOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.temperature, rhs.temperature) && MessagesPigeonInternal.deepEquals(lhs.maxOutputTokens, rhs.maxOutputTokens)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EdgeGenAIGenerationOptions")
    MessagesPigeonInternal.deepHash(value: temperature, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxOutputTokens, hasher: &hasher)
  }

  public var description: String {
    return "EdgeGenAIGenerationOptions(temperature: \(String(describing: temperature)), maxOutputTokens: \(String(describing: maxOutputTokens)))"
  }
}

/// A single download progress update.
///
/// Generated class from Pigeon that represents data sent in messages.
struct EdgeGenAIDownloadProgress: Hashable, CustomStringConvertible {
  /// The current status of the download.
  var status: EdgeGenAIDownloadStatus
  /// The total number of bytes downloaded so far. Only populated when
  /// [status] is [EdgeGenAIDownloadStatus.inProgress].
  var bytesDownloaded: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EdgeGenAIDownloadProgress? {
    let status = pigeonVar_list[0] as! EdgeGenAIDownloadStatus
    let bytesDownloaded: Int64? = nilOrValue(pigeonVar_list[1])

    return EdgeGenAIDownloadProgress(
      status: status,
      bytesDownloaded: bytesDownloaded
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      bytesDownloaded,
    ]
  }
  static func == (lhs: EdgeGenAIDownloadProgress, rhs: EdgeGenAIDownloadProgress) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.bytesDownloaded, rhs.bytesDownloaded)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EdgeGenAIDownloadProgress")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bytesDownloaded, hasher: &hasher)
  }

  public var description: String {
    return "EdgeGenAIDownloadProgress(status: \(String(describing: status)), bytesDownloaded: \(String(describing: bytesDownloaded)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EdgeGenAIAvailability(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EdgeGenAIFeature(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EdgeGenAIRewriteStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EdgeGenAIDownloadStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return EdgeGenAIToolDefinition.fromList(self.readValue() as! [Any?])
    case 134:
      return EdgeGenAIGenerationOptions.fromList(self.readValue() as! [Any?])
    case 135:
      return EdgeGenAIDownloadProgress.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? EdgeGenAIAvailability {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? EdgeGenAIFeature {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? EdgeGenAIRewriteStyle {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? EdgeGenAIDownloadStatus {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? EdgeGenAIToolDefinition {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? EdgeGenAIGenerationOptions {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? EdgeGenAIDownloadProgress {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol EdgeGenAIHostApi {
  func checkAvailability(feature: EdgeGenAIFeature, completion: @escaping (Result<EdgeGenAIAvailability, Error>) -> Void)
  /// Stores the request for the next `generateContentChunk` event channel
  /// subscription to use.
  ///
  /// [sessionId] identifies the `EdgeGenAIPrompt` instance making the call,
  /// so each instance gets its own isolated conversation when [useMemory]
  /// is true; when false, it's a stateless, one-off call that neither reads
  /// nor updates that instance's remembered conversation. [image] is an
  /// optional encoded image (for example PNG or JPEG bytes) sent to the
  /// model alongside [prompt]. [tools] describes the tools the model may
  /// call during generation; when it does, the platform side invokes the
  /// matching Dart executor through `EdgeGenAIToolExecutorApi.callTool`.
  ///
  /// Event channels can't carry parameters, so callers must invoke this
  /// immediately before listening to the `generateContentChunk` stream.
  func startGenerateContent(sessionId: String, prompt: String, options: EdgeGenAIGenerationOptions?, useMemory: Bool, image: FlutterStandardTypedData?, tools: [EdgeGenAIToolDefinition]) throws
  /// Clears the conversation history remembered for [sessionId] so that
  /// instance's next `generateContent` call starts a fresh conversation.
  func resetConversation(sessionId: String) throws
  /// Summarizes [text] and returns the summary.
  func summarize(text: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Proofreads [text] and returns the corrected text.
  func proofread(text: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Rewrites [text] in the given [style] and returns the rewritten text.
  func rewrite(text: String, style: EdgeGenAIRewriteStyle, completion: @escaping (Result<String, Error>) -> Void)
  /// Describes the image encoded in [imageBytes] (for example PNG or JPEG
  /// bytes) and returns the description.
  func describeImage(imageBytes: FlutterStandardTypedData, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class EdgeGenAIHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `EdgeGenAIHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EdgeGenAIHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let checkAvailabilityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.checkAvailability\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkAvailabilityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let featureArg = args[0] as! EdgeGenAIFeature
        api.checkAvailability(feature: featureArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkAvailabilityChannel.setMessageHandler(nil)
    }
    /// Stores the request for the next `generateContentChunk` event channel
    /// subscription to use.
    ///
    /// [sessionId] identifies the `EdgeGenAIPrompt` instance making the call,
    /// so each instance gets its own isolated conversation when [useMemory]
    /// is true; when false, it's a stateless, one-off call that neither reads
    /// nor updates that instance's remembered conversation. [image] is an
    /// optional encoded image (for example PNG or JPEG bytes) sent to the
    /// model alongside [prompt]. [tools] describes the tools the model may
    /// call during generation; when it does, the platform side invokes the
    /// matching Dart executor through `EdgeGenAIToolExecutorApi.callTool`.
    ///
    /// Event channels can't carry parameters, so callers must invoke this
    /// immediately before listening to the `generateContentChunk` stream.
    let startGenerateContentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.startGenerateContent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startGenerateContentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let promptArg = args[1] as! String
        let optionsArg: EdgeGenAIGenerationOptions? = nilOrValue(args[2])
        let useMemoryArg = args[3] as! Bool
        let imageArg: FlutterStandardTypedData? = nilOrValue(args[4])
        let toolsArg = args[5] as! [EdgeGenAIToolDefinition]
        do {
          try api.startGenerateContent(sessionId: sessionIdArg, prompt: promptArg, options: optionsArg, useMemory: useMemoryArg, image: imageArg, tools: toolsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startGenerateContentChannel.setMessageHandler(nil)
    }
    /// Clears the conversation history remembered for [sessionId] so that
    /// instance's next `generateContent` call starts a fresh conversation.
    let resetConversationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.resetConversation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetConversationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        do {
          try api.resetConversation(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resetConversationChannel.setMessageHandler(nil)
    }
    /// Summarizes [text] and returns the summary.
    let summarizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.summarize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      summarizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        api.summarize(text: textArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      summarizeChannel.setMessageHandler(nil)
    }
    /// Proofreads [text] and returns the corrected text.
    let proofreadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.proofread\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      proofreadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        api.proofread(text: textArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      proofreadChannel.setMessageHandler(nil)
    }
    /// Rewrites [text] in the given [style] and returns the rewritten text.
    let rewriteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.rewrite\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rewriteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        let styleArg = args[1] as! EdgeGenAIRewriteStyle
        api.rewrite(text: textArg, style: styleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      rewriteChannel.setMessageHandler(nil)
    }
    /// Describes the image encoded in [imageBytes] (for example PNG or JPEG
    /// bytes) and returns the description.
    let describeImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.describeImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      describeImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageBytesArg = args[0] as! FlutterStandardTypedData
        api.describeImage(imageBytes: imageBytesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      describeImageChannel.setMessageHandler(nil)
    }
  }
}

/// Calls from the platform side back into Dart, where tool implementations
/// live.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol EdgeGenAIToolExecutorApiProtocol {
  /// Runs the Dart executor of the tool named [toolName] (registered by the
  /// `EdgeGenAIPrompt` instance identified by [sessionId]) with the
  /// JSON-encoded [argumentsJson] the model provided, and returns the
  /// tool's result for the model to continue generating with.
  func callTool(sessionId sessionIdArg: String, toolName toolNameArg: String, argumentsJson argumentsJsonArg: String, completion: @escaping (Result<String, PigeonError>) -> Void)
}
class EdgeGenAIToolExecutorApi: EdgeGenAIToolExecutorApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Runs the Dart executor of the tool named [toolName] (registered by the
  /// `EdgeGenAIPrompt` instance identified by [sessionId]) with the
  /// JSON-encoded [argumentsJson] the model provided, and returns the
  /// tool's result for the model to continue generating with.
  func callTool(sessionId sessionIdArg: String, toolName toolNameArg: String, argumentsJson argumentsJsonArg: String, completion: @escaping (Result<String, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIToolExecutorApi.callTool\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdArg, toolNameArg, argumentsJsonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! String
        completion(.success(result))
      }
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Each method below is a separate event channel, so downloads of different
/// features can run (and report progress) independently.
///
/// On iOS there's nothing for the app to download — Apple Intelligence is
/// enabled system-wide in Settings — so every download stream immediately
/// emits a single `completed` event.
class PromptDownloadProgressStreamHandler: PigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: PromptDownloadProgressStreamHandler) {
    var channelName = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.promptDownloadProgress"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<EdgeGenAIDownloadProgress>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class SummarizationDownloadProgressStreamHandler: PigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: SummarizationDownloadProgressStreamHandler) {
    var channelName = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.summarizationDownloadProgress"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<EdgeGenAIDownloadProgress>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class ProofreadingDownloadProgressStreamHandler: PigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: ProofreadingDownloadProgressStreamHandler) {
    var channelName = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.proofreadingDownloadProgress"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<EdgeGenAIDownloadProgress>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class RewritingDownloadProgressStreamHandler: PigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: RewritingDownloadProgressStreamHandler) {
    var channelName = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.rewritingDownloadProgress"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<EdgeGenAIDownloadProgress>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class ImageDescriptionDownloadProgressStreamHandler: PigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: ImageDescriptionDownloadProgressStreamHandler) {
    var channelName = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.imageDescriptionDownloadProgress"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<EdgeGenAIDownloadProgress>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class GenerateContentChunkStreamHandler: PigeonEventChannelWrapper<String> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: GenerateContentChunkStreamHandler) {
    var channelName = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.generateContentChunk"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<String>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
