// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.manukj.edge_gen_ai

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** The availability of an on-device generative AI feature. */
enum class EdgeGenAIAvailability(val raw: Int) {
  /** The feature is available and ready to use. */
  AVAILABLE(0),
  /**
   * The device supports the feature, but it still needs to download (for
   * example, Android's Gemini Nano feature is downloadable/downloading).
   */
  DOWNLOADABLE(1),
  /**
   * The device supports the feature, but the user hasn't enabled the
   * OS-level AI feature yet (for example, Apple Intelligence is turned
   * off).
   */
  NOT_YET_READY(2),
  /** The device or OS version doesn't support the on-device feature. */
  UNAVAILABLE(3);

  companion object {
    fun ofRaw(raw: Int): EdgeGenAIAvailability? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The on-device generative AI features exposed by this plugin.
 *
 * On Android each feature is a distinct ML Kit GenAI client with its own
 * independent availability/download lifecycle; on iOS they all map to the
 * single system Foundation Models availability.
 */
enum class EdgeGenAIFeature(val raw: Int) {
  /** The general-purpose prompt feature (`EdgeGenAIPrompt`). */
  PROMPT(0),
  /** The text summarization feature (`EdgeGenAISummarizer`). */
  SUMMARIZATION(1),
  /** The proofreading feature (`EdgeGenAIProofreader`). */
  PROOFREADING(2),
  /** The text rewriting feature (`EdgeGenAIRewriter`). */
  REWRITING(3),
  /** The image description feature (`EdgeGenAIImageDescriber`). */
  IMAGE_DESCRIPTION(4);

  companion object {
    fun ofRaw(raw: Int): EdgeGenAIFeature? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The style `EdgeGenAIRewriter` rewrites text into.
 *
 * Matches the output types of Android's ML Kit GenAI Rewriting API; on iOS
 * each style becomes a task-specific instruction to the system model.
 */
enum class EdgeGenAIRewriteStyle(val raw: Int) {
  /** Rephrases the text while keeping its meaning and length. */
  REPHRASE(0),
  /** Expands on the text with more detail. */
  ELABORATE(1),
  /** Adds fitting emoji to the text. */
  EMOJIFY(2),
  /** Shortens the text while keeping its meaning. */
  SHORTEN(3),
  /** Rewrites the text in a casual, friendly tone. */
  FRIENDLY(4),
  /** Rewrites the text in a formal, professional tone. */
  PROFESSIONAL(5);

  companion object {
    fun ofRaw(raw: Int): EdgeGenAIRewriteStyle? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The status of an on-device model download. */
enum class EdgeGenAIDownloadStatus(val raw: Int) {
  /** The download has started. */
  STARTED(0),
  /** The download is in progress. */
  IN_PROGRESS(1),
  /** The download finished and the model is ready to use. */
  COMPLETED(2);

  companion object {
    fun ofRaw(raw: Int): EdgeGenAIDownloadStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The model-facing description of a tool the app exposes to the model.
 *
 * The tool's implementation stays in Dart (see `EdgeGenAITool.onCall`);
 * only this schema crosses to the platform side, which calls back into
 * Dart via `EdgeGenAIToolExecutorApi` when the model invokes the tool.
 *
 * The description field is named `descriptionText` (not `description`)
 * because Pigeon reserves `description` for Swift's NSObject property.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EdgeGenAIToolDefinition (
  /** The tool's unique name. */
  val name: String,
  /** What the tool does, so the model knows when to call it. */
  val descriptionText: String,
  /**
   * A JSON Schema document (as JSON text) describing the tool's arguments
   * object: `{"type": "object", "properties": {...}, "required": [...]}`.
   *
   * It's carried as JSON text rather than typed Pigeon classes because
   * schemas are recursive (objects nest objects, arrays have item
   * schemas), which Pigeon data classes can't express. The supported
   * subset — mirroring what Foundation Models' `DynamicGenerationSchema`
   * can enforce — is: `type` (string/number/integer/boolean/array/object),
   * `description`, `enum` (strings), `minimum`/`maximum` (numbers),
   * `items`/`minItems`/`maxItems` (arrays), and `properties`/`required`
   * (objects). The `EdgeGenAIToolSchema` factories in Dart only build
   * this subset.
   */
  val parametersSchemaJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EdgeGenAIToolDefinition {
      val name = pigeonVar_list[0] as String
      val descriptionText = pigeonVar_list[1] as String
      val parametersSchemaJson = pigeonVar_list[2] as String
      return EdgeGenAIToolDefinition(name, descriptionText, parametersSchemaJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      descriptionText,
      parametersSchemaJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EdgeGenAIToolDefinition
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.descriptionText, other.descriptionText) && MessagesPigeonUtils.deepEquals(this.parametersSchemaJson, other.parametersSchemaJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.descriptionText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.parametersSchemaJson)
    return result
  }
  override fun toString(): String {
    return "EdgeGenAIToolDefinition(name=$name, descriptionText=$descriptionText, parametersSchemaJson=$parametersSchemaJson)"
  }
}

/**
 * Optional parameters controlling how the model generates its response.
 *
 * Only fields supported by both Android and iOS are exposed here.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EdgeGenAIGenerationOptions (
  /**
   * Controls the randomness of the output. Higher values produce more
   * creative (less predictable) responses.
   */
  val temperature: Double? = null,
  /** The maximum number of tokens the model may generate in its response. */
  val maxOutputTokens: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EdgeGenAIGenerationOptions {
      val temperature = pigeonVar_list[0] as Double?
      val maxOutputTokens = pigeonVar_list[1] as Long?
      return EdgeGenAIGenerationOptions(temperature, maxOutputTokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      temperature,
      maxOutputTokens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EdgeGenAIGenerationOptions
    return MessagesPigeonUtils.deepEquals(this.temperature, other.temperature) && MessagesPigeonUtils.deepEquals(this.maxOutputTokens, other.maxOutputTokens)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.temperature)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxOutputTokens)
    return result
  }
  override fun toString(): String {
    return "EdgeGenAIGenerationOptions(temperature=$temperature, maxOutputTokens=$maxOutputTokens)"
  }
}

/**
 * A single download progress update.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EdgeGenAIDownloadProgress (
  /** The current status of the download. */
  val status: EdgeGenAIDownloadStatus,
  /**
   * The total number of bytes downloaded so far. Only populated when
   * [status] is [EdgeGenAIDownloadStatus.inProgress].
   */
  val bytesDownloaded: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EdgeGenAIDownloadProgress {
      val status = pigeonVar_list[0] as EdgeGenAIDownloadStatus
      val bytesDownloaded = pigeonVar_list[1] as Long?
      return EdgeGenAIDownloadProgress(status, bytesDownloaded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      bytesDownloaded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EdgeGenAIDownloadProgress
    return MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.bytesDownloaded, other.bytesDownloaded)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bytesDownloaded)
    return result
  }
  override fun toString(): String {
    return "EdgeGenAIDownloadProgress(status=$status, bytesDownloaded=$bytesDownloaded)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EdgeGenAIAvailability.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EdgeGenAIFeature.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EdgeGenAIRewriteStyle.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EdgeGenAIDownloadStatus.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EdgeGenAIToolDefinition.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EdgeGenAIGenerationOptions.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EdgeGenAIDownloadProgress.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EdgeGenAIAvailability -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is EdgeGenAIFeature -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is EdgeGenAIRewriteStyle -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is EdgeGenAIDownloadStatus -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is EdgeGenAIToolDefinition -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is EdgeGenAIGenerationOptions -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is EdgeGenAIDownloadProgress -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface EdgeGenAIHostApi {
  fun checkAvailability(feature: EdgeGenAIFeature, callback: (Result<EdgeGenAIAvailability>) -> Unit)
  /**
   * Stores the request for the next `generateContentChunk` event channel
   * subscription to use.
   *
   * [sessionId] identifies the `EdgeGenAIPrompt` instance making the call,
   * so each instance gets its own isolated conversation when [useMemory]
   * is true; when false, it's a stateless, one-off call that neither reads
   * nor updates that instance's remembered conversation. [image] is an
   * optional encoded image (for example PNG or JPEG bytes) sent to the
   * model alongside [prompt]. [tools] describes the tools the model may
   * call during generation; when it does, the platform side invokes the
   * matching Dart executor through `EdgeGenAIToolExecutorApi.callTool`.
   *
   * Event channels can't carry parameters, so callers must invoke this
   * immediately before listening to the `generateContentChunk` stream.
   */
  fun startGenerateContent(sessionId: String, prompt: String, options: EdgeGenAIGenerationOptions?, useMemory: Boolean, image: ByteArray?, tools: List<EdgeGenAIToolDefinition>)
  /**
   * Clears the conversation history remembered for [sessionId] so that
   * instance's next `generateContent` call starts a fresh conversation.
   */
  fun resetConversation(sessionId: String)
  /** Summarizes [text] and returns the summary. */
  fun summarize(text: String, callback: (Result<String>) -> Unit)
  /** Proofreads [text] and returns the corrected text. */
  fun proofread(text: String, callback: (Result<String>) -> Unit)
  /** Rewrites [text] in the given [style] and returns the rewritten text. */
  fun rewrite(text: String, style: EdgeGenAIRewriteStyle, callback: (Result<String>) -> Unit)
  /**
   * Describes the image encoded in [imageBytes] (for example PNG or JPEG
   * bytes) and returns the description.
   */
  fun describeImage(imageBytes: ByteArray, callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by EdgeGenAIHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `EdgeGenAIHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EdgeGenAIHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.checkAvailability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureArg = args[0] as EdgeGenAIFeature
            api.checkAvailability(featureArg) { result: Result<EdgeGenAIAvailability> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.startGenerateContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val promptArg = args[1] as String
            val optionsArg = args[2] as EdgeGenAIGenerationOptions?
            val useMemoryArg = args[3] as Boolean
            val imageArg = args[4] as ByteArray?
            val toolsArg = args[5] as List<EdgeGenAIToolDefinition>
            val wrapped: List<Any?> = try {
              api.startGenerateContent(sessionIdArg, promptArg, optionsArg, useMemoryArg, imageArg, toolsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.resetConversation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.resetConversation(sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.summarize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            api.summarize(textArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.proofread$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            api.proofread(textArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.rewrite$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val styleArg = args[1] as EdgeGenAIRewriteStyle
            api.rewrite(textArg, styleArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIHostApi.describeImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imageBytesArg = args[0] as ByteArray
            api.describeImage(imageBytesArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Calls from the platform side back into Dart, where tool implementations
 * live.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class EdgeGenAIToolExecutorApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by EdgeGenAIToolExecutorApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /**
   * Runs the Dart executor of the tool named [toolName] (registered by the
   * `EdgeGenAIPrompt` instance identified by [sessionId]) with the
   * JSON-encoded [argumentsJson] the model provided, and returns the
   * tool's result for the model to continue generating with.
   */
  fun callTool(sessionIdArg: String, toolNameArg: String, argumentsJsonArg: String, callback: (Result<String>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIToolExecutorApi.callTool$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdArg, toolNameArg, argumentsJsonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as String
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * Each method below is a separate event channel, so downloads of different
 * features can run (and report progress) independently.
 *
 * On iOS there's nothing for the app to download — Apple Intelligence is
 * enabled system-wide in Settings — so every download stream immediately
 * emits a single `completed` event.
 */
abstract class PromptDownloadProgressStreamHandler : MessagesPigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: PromptDownloadProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.promptDownloadProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<EdgeGenAIDownloadProgress>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<EdgeGenAIDownloadProgress>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class SummarizationDownloadProgressStreamHandler : MessagesPigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: SummarizationDownloadProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.summarizationDownloadProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<EdgeGenAIDownloadProgress>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<EdgeGenAIDownloadProgress>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class ProofreadingDownloadProgressStreamHandler : MessagesPigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ProofreadingDownloadProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.proofreadingDownloadProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<EdgeGenAIDownloadProgress>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<EdgeGenAIDownloadProgress>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class RewritingDownloadProgressStreamHandler : MessagesPigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: RewritingDownloadProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.rewritingDownloadProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<EdgeGenAIDownloadProgress>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<EdgeGenAIDownloadProgress>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class ImageDescriptionDownloadProgressStreamHandler : MessagesPigeonEventChannelWrapper<EdgeGenAIDownloadProgress> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ImageDescriptionDownloadProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.imageDescriptionDownloadProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<EdgeGenAIDownloadProgress>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<EdgeGenAIDownloadProgress>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class GenerateContentChunkStreamHandler : MessagesPigeonEventChannelWrapper<String> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: GenerateContentChunkStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.edge_gen_ai.EdgeGenAIEventApi.generateContentChunk"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<String>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<String>) {}

override fun onCancel(p0: Any?) {}
}
      
